#!/Users/chenxg/anaconda3/anaconda3/bin/python
# -*- coding: utf-8 -*-
import re
import sys
import os
root_path = os.path.dirname(os.path.dirname(os.path.dirname(os.path.realpath(__file__))))
sys.path.append(root_path)
from pelican.tools.pelican_import import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
